name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.20
  - python=3.8
  - pip=20.3.3
  - requests=2.24.0
  - mlflow=2.0.1
  - pip:
      - wandb==0.13.4
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components

